config/routes.rb
Rails.application.routes.draw do
 root to: 'toppages#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 get 'signup', to: 'users#new'
 resources :users 
 resources :sakes, only: [:show, :new]
 resources :relationships, only: [:create, :destroy]
 resources :ownerships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user
  belongs_to :sake
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/sake.rb
class Sake < ApplicationRecord
  
  validates :identify_code, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :furigana, presence: true, length: { maximum: 255 }
  
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :wants
  has_many :want_users, through: :wants, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: {maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :ownerships
  has_many :sakes, through: :ownerships
  has_many :wants
  has_many :want_sakes, through: :wants, source: :sake

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
  relationship = self.relationships.find_by(follow_id: other_user.id)
  relationship.destroy if relationship
  end

  def following?(other_user)
  self.followings.include?(other_user)
  end
  
  def want(sake)
    self.wants.find_or_create_by(sake_id: sake.id)
  end
  
  def unwant(sake)
    want = self.wants.find_by(sake_id: sake.id)
    want.destroy if want
  end
  
  def want?(sake)
    self.want_sakes.include?(sake)
  end
end

app/models/want.rb
class Want < Ownership
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def create
    @sake = Sake.find_or_initialize_by(name: params[:sake_name])
    
    require 'open-uri'
  
    api_key =ENV['SAKENOTE_API_TOKEN'] 
    unless @sake.persisted?
      uri = URI.encode("https://www.sakenote.com/api/v1/sakes?token=#{api_key}&sake_name=#{params[:sake_name]}")
      res = open(uri)
      json_string = res.read
      results = JSON.parse(json_string, { symbolize_names: true })[:sakes]
      
      results.each do |result|
       @sake.identify_code = result[:sake_identify_code]
       @sake.name = result[:sake_name]
       @sake.furigana = result[:sake_furigana]
       @sake.maker_name = result[:maker_name]
       @sake.maker_address = result[:maker_address]
       @sake.maker_url = result[:maker_url]
       @sake.save
      end
    end
    
    if params[:type] == 'Want'
      current_user.want(@sake)
      flash[:success] = '商品を Wantしました'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @sake = Sake.find(params[:sake_id])
    
    if params[:type] == 'Want'
      current_user.unwant(@sake)
      flash[:success] = '商品の Want を解除しました'
    end
    
    
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:follow_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:follow_id])
    current_user.unfollow(@user)
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  before_action :require_user_logged_in
  
  def show
    @sake = Sake.find(params[:id])
    @want_users = @sake.want_users
  end
  
  def new
   
    require 'open-uri'
    
    
    @keyword = params[:keyword]
    api_key =ENV['SAKENOTE_API_TOKEN'] 
    if @keyword.present?
      uri = URI.encode("https://www.sakenote.com/api/v1/sakes?token=#{api_key}&sake_name=#{@keyword}")
      res = open(uri)
      json_string = res.read
      results = JSON.parse(json_string, { symbolize_names: true })[:sakes]
      
      @sakes = []

      results.each do |result|
        #binding.pry
       sake = Sake.find_or_initialize_by(identify_code: result[:sake_identify_code])
       sake.identify_code = result[:sake_identify_code]
       sake.name = result[:sake_name]
       sake.furigana = result[:sake_furigana]
       sake.maker_name = result[:maker_name]
       sake.maker_address = result[:maker_address]
       sake.maker_url = result[:maker_url]
       @sakes.push(sake)
      end
      
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @sakes = Sake.order('updated_at DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :following, :followers]
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @sakes = @user.sakes
    @count_want = @user.want_sakes.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = '正常に更新完了！'
      redirect_to @user
    else
      flash.now[:danger] = '更新に失敗！'
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    flash[:success] ='ユーザを削除しました。'
    redirect_to users_path
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2019 SAKEMENU.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SakeMenu</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li>
               <%= link_to new_sake_path do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                日本酒を検索
              <% end %>
          </li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="gravatar">
                <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
              </span>
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'マイページ', user_path(current_user) %>
              </li>
              <li>
                <%= link_to 'ユーザ編集', edit_user_path(current_user) %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
               <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '新規登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SakeMenu</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/ownerships/_want_button.html.erb
<% if current_user.want?(sake) %>
  <%= form_tag(ownership_path(sake.id), method: :delete) do %>
    <%= hidden_field_tag :sake_id, sake.id %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Unwant', class: 'btn btn-success btn-xs' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :sake_name, sake.name %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want it', class: 'btn btn-primary btn-xs' %>
  <% end %>
<% end %>

app/views/relationships/_follow_button.html.erb
<div id="follow_form_<%= user.id %>">
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, remote:true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-xs' %>
    <% end %>
  <% else %>
   <%= form_for(current_user.relationships.build, remote:true) do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'Follow', class: 'btn btn-primary btn-xs' %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#follow_form_<%= @user.id %>").html("<%=j render 'relationships/follow_button', user: @user %>");

app/views/relationships/destroy.js.erb
$("#follow_form_<%= @user.id %>").html("<%=j render 'relationships/follow_button', user: @user %>");

app/views/sakes/_sakes.html.erb
<% if @sakes.present? %>
  <div class="row">
    <% @sakes.each do |sake| %>
      <div class="sakes">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
                <コード><%= sake.identify_code %>
              <% if logged_in? %>
                <%= render 'ownerships/want_button', sake: sake %>
              <% end %>
            </div>
            <div class="panel-body">
              <p class="sake-title"> 
              <酒名><%= sake.name %><br>
              <ふりがな><%= sake.furigana %></p>
              <酒蔵><%= sake.maker_name %><br>
              <酒蔵住所><br><%= sake.maker_address %><br>
              <酒蔵URL><br><%= link_to 'Search', sake.maker_url %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/sakes/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_sake_path, method: :get, class: 'form-inline') do %>
      <div class="form-gruup">
        <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "酒名(漢字、ひらがな)を入力", size: 40 %>
      </div>
      <%= submit_tag '酒を検索', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'sakes', sakes: @sakes %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
<div class="cover">
  <div class="cover-inner">
    <div class="cover-contents">
      <h1>日本のお酒でつながる出会い</h1>
      <% unless logged_in? %>
        <%= link_to 'はじめる', signup_path, class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
<ul class="media-list">
  <% users.each do |user| %>
  <li class="media">
    <div class="media-center">
      <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
    </div>
    <div class="media-body">
      <div>
        <%= user.name %>
      </div>
      <div>
        <p><%= link_to 'プロフィール', user_path(user) %></p>
      </div>
      <div>
        <% unless current_user == user %>
          <%= render 'relationships/follow_button', user:  user %>
        <% end %>
      </div>
    </div>
  </li>
  <% end %>
</ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
 <div class="text-center">
    <h1>ユーザ情報編集</h1>
 </div>
 <div class="row">
  <div class="col-xs-offset-3 col-xs-6">
   <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "変更する", class: "btn btn-primary" %>
  <% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-center">
            <%= f.submit '登録する', class: 'btn btn-success btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
    <%= render 'relationships/follow_button', user:  @user %>
    <% if current_user ==@user %>
      <%= link_to "ユーザ削除", @user, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-md' %>
    <% end %>
  </div>
  <div class="status text-center">
    <ul>
      <li>
        <div class="status-label">WANT</div>
        <div id="want_count" class="status-value">
          <%= @count_want %>
        </div>
      </li>
    </ul>
  </div>
</div>
<%= render 'sakes/sakes', sakes: @sakes %>